name: Movie Booking CI/CD

on:
  push:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd server && npm install

      - name: Run tests
        run: cd server && npm test
        env:
          MONGODB: ${{ secrets.MONGODB }}
          RAZORPAY_APIKEY: ${{ secrets.RAZORPAY_APIKEY }}
          RAZORPAY_SECRET: ${{ secrets.RAZORPAY_SECRET }}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          PORT: 3000

  deploy-to-aws:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy via SSH to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Navigate to your project directory on EC2
            cd /home/ubuntu/Book-Movie-Ticket # Ensure this matches your folder name on EC2!

            # 2. Pull the latest code from GitHub
            git pull origin main

            # 3. Build the React frontend (client)
            cd client
            npm install
            npm run build

            # 4. Install backend dependencies and restart PM2
            cd ../server
            npm install
            pm2 restart movie-backend || pm2 start index.js --name "movie-backend"