name: Movie Booking CI/CD

on:
  push:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd server && npm install

      - name: Run tests
        run: cd server && npm test
        env:
          MONGODB_URI: ${{ secrets.MONGODB }}
          RAZORPAY_APIKEY: ${{ secrets.RAZORPAY_APIKEY }}
          RAZORPAY_SECRET: ${{ secrets.RAZORPAY_SECRET }}
          PORT: 3000

  deploy:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps: 
      - name: Deploy on Render
        run: curl ${{secrets.RENDER_DEPLOY_HOOK_URL}}